# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

linters-settings:
  dupl:
    threshold: 120
  funlen:
    lines: 120
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/x1ah/gena
  mnd:
    settings:
      checks: argument,case,condition,return
  lll:
    line-length: 140
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-dirs:
    - internal/proto
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - gosec
    - linters:
        - gocritic
      text: "unnecessaryDefer:"
    - text: 'declaration of "(err|ctx)" shadows declaration at'
      linters:
        - govet
    - path: generators/tilde\.go
      linters:
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
